name: 'Epicentrismo em Debate'

on:
  push:
    paths: 
      - epicentrismo.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: docker://quay.io/weltonrodrigo/youtube-to-anchorrm:episode_path
        timeout-minutes: 10
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          PODCAST_TITLE: "Epicentrismo em Debate - Conscienciologia"
          EPISODE_PATH: /github/workspace/
          EPISODE_FILE: epicentrismo.json
          POSTPROCESSOR_ARGS: "ExtractAudio+ffmpeg:-ac 1 -af silenceremove=1:0:-50dB,afade=t=in:d=5"
          SAVE_AS_DRAFT: false
          SET_PUBLISH_DATE: true
          URL_IN_DESCRIPTION: true
