name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths: 
      - epicentrismo.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@V0.1.8
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          POSTPROCESSOR_ARGS: "ffmpeg:-ac 1"
          SAVE_AS_DRAFT: true
