name: 'Epicentrismo em Debate'

on:
  push:
    paths: 
      - epicentrismo.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: weltonrodrigo/youtube-to-anchorfm@multi-show
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace/
          EPISODE_CONFIG: epicentrismo.json
          POSTPROCESSOR_ARGS: "ffmpeg:-ac 1 -af silenceremove=1:0:-50dB"
          SAVE_AS_DRAFT: true
