name: 'Tertúlia Matinal'

on:
  push:
    paths: 
      - tertuliamatinal.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: docker://quay.io/weltonrodrigo/youtube-to-anchorrm:episode_path
        timeout-minutes: 10
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL_TERTULIAMATINAL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD_TERTULIAMATINAL }}
          EPISODE_PATH: /github/workspace/
          EPISODE_CONFIG: tertuliamatinal.json
          POSTPROCESSOR_ARGS: "ffmpeg:-ac 1 -af silenceremove=1:0:-50dB"
          SAVE_AS_DRAFT: true
          SET_PUBLISH_DATE: true
          URL_IN_DESCRIPTION: true
