name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    # paths: 
    #   - episode.json
    #   - .github/worflows/upload.yml
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: weltonrodrigo/youtube-to-anchorfm@master
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: .